### ISSUE TITLE
It is not compatible with the new ros

### ISSUE THREAD

**Issue by sinamr88** [felixduvallet/allegro-hand-ros#23]
I tested with Kinetic and it is not compatible as there is no libpcan for Kinetic.  To solve it, I installed the libpcan from the source, which you can find it here:https://github.com/ipa320/cob_extern.

But, this version of libpcan is not compatible with Ubuntu 16.04. The problem can be fixed by editing " cob_extern/libpcan/Makefile.tarball" and the following changes must be applied:
TARBALL = build/peak-linux-driver-7.15.2.tar.gz
TARBALL_URL = http://www.peak-system.com/fileadmin/media/linux/files/peak-linux-driver-7.15.2.tar.gz
.
.
.
SOURCE_DIR = build/peak-linux-driver-7.15.2.tar.gz
MD5SUM_FILE = peak-linux-driver-7.15.2.tar.gz.md5sum

Everyone will be happy and we can compile all the packages (libpcan and allegro-hand-ros)...But when we send any command to the hand, the hand dies or does not move correctly. I just tested the package with the left hand, Ubuntu 16.04 and the ROS version was kinetic.

**Comment by felixduvallet** [comment]
this sounds like a libpcan problem, which is not available for kinetic yet.
