### ISSUE TITLE
Allegro hand in ROS indigo fails to launch

### ISSUE THREAD

**Issue by balakumar-s** [felixduvallet/allegro-hand-ros#24]
I am using ROS indigo with Ubuntu 14.04 kernel version- 4.2.0-42-generic
The launch file works very rarely after many reboots of the hand. 
I get this error every time:

[ INFO] [1469484257.800466466]: Start controller with polling = 1
[ INFO] [1469484257.800564523]: Polling = true.
[ WARN] [1469484258.702291830]: unknown command 0, src 1, to 0, len 4
[ WARN] [1469484258.702334084]: readDevices: lID -1
[ERROR] [1469484258.702359157]: Emergency stop in Update()
[ERROR] [1469484258.702387303]: Allegro Hand Node is Shutting Down! (Emergency Stop)

I am using a usb-pcan ([link](http://www.phytools.com/PEAK_IPEH_002021_PCAN_USB_Adapter_p/ipeh-002021.htm)) to connect the hand to a pc through USB 2.0 (USB 3.0 has no improvement either). I can run the linux allegro hand driver without any issues. Has someone encountered this issue before?

**Comment by felixduvallet** [comment]
Apologies about the delay getting to this.

Unfortunately the driver code isn't my doing (it's primarily from the original simlabs version), so it's difficult to diagnose. Have you tried adding some debugging output in `_parseCANMsg` or `_readDevices`?

Does the hand _eventually_ connect or does it not work at all?

**Comment by felixduvallet** [comment]
I'm closing this, feel free to open a new issue with more details.

**Comment by kalyanvasudev** [comment]
Hi, I am seeing the same issue on Ubuntu 16.04 with ROS kinetic. I am using [this](https://www.gridconnect.com/products/can-usb-fd-adapter-pcan-usb-fd) PEAK CAN device.

**Comment by kalyanvasudev** [comment]
@balakumar-s  how did you solve this problem?

**Comment by jackklawitter** [comment]
@kalyanvasudev Apologies as I know it's been many years but I am currently experience the same issue also using Ubuntu 16.04 and ROS kinetic. Is there any chance you can recall what the issue was? Thank you!
