### ISSUE TITLE
Torque issue 

### ISSUE THREAD

**Issue by raff44** [felixduvallet/allegro-hand-ros#25]
Hello,

It is more of a question, I have noticed that the motors are most powerful in envelop mode, is it possible to change the torque of the motors in different modes ? For example pinch or 4 finger grasp.

Thanks.

**Comment by felixduvallet** [comment]
Hey,
You may be able to change the behavior by setting the gains for P in the configuration file, for example [this one][1].

Unfortunately the "grasp" controller parameters are not directly accessible (AFAIK), they run under a different controller.

Hope that helps.

[1]: https://github.com/felixduvallet/allegro-hand-ros/blob/master/allegro_hand_parameters/gains_pd.yaml
