### ISSUE TITLE
Poses of links goes to 0,0,0 when Gazebo simulation is started

### ISSUE THREAD

**Issue by tamertemizer** [felixduvallet/allegro-hand-ros#26]
The robot looks fine when dynamics is not open (all links are in their correct places). But when the simulation starts all links' xyz and rpy goes to 0,0,0. This makes the robot all parts to be crammed with each other and create a jumbled mess. There are no errors in Gazebo command line about illegal collisions.  Using Ros Indigo.
![default_gzclient_camera 0 -2017-10-15t19_39_53 689905](https://user-images.githubusercontent.com/14349978/31586929-ffa9fa26-b1e0-11e7-8b3c-bfb827396e3a.jpg)
![default_gzclient_camera 0 -2017-10-15t19_41_00 270050](https://user-images.githubusercontent.com/14349978/31586930-ffcfb3d8-b1e0-11e7-9d3e-339cb19f2582.jpg)

**Comment by felixduvallet** [comment]
Hi,
Gazebo support is basically [pre-alpha](https://github.com/felixduvallet/allegro-hand-ros#gazebo-alpha-support) at this point, so I would expect lots of broken things (as you found out).
If you do manage to get something working, please contribute it back!
Felix

**Comment by eterpega** [comment]
The model works well if you change as below 
  1) the parameters to zero at each joints
          <dynamics damping="0" friction="0"/>
  2) modify thumb link collisions or palm_link_z value (because, thumb_tip penetrated to ground at initial position)
